org.gradle.jvmargs = -Xmx6096M
org.gradle.parallel = true
org.gradle.daemon = false

java_version = 17

# Mc stuff
minecraft_version = 1.20.1
enabled_platforms = fabric,forge
pack_format_number = 15
yarn_mappings = 1.20.1+build.1

# Mod stuff
mod_id = norabotics
mod_name = Robotics
mod_version = 1.0.3
mod_license = MIT License
mod_group_id = com.io
mod_authors = Fayenora
mod_description = Robotics adds programmable and customizable robots to Minecraft.
mod_homepage = https://modrinth.com/mod/robotics
mod_github = https://github.com/Fayenora/Robotics
mod_credits = A huge thanks to the Forge team for making modding so accessible to everyone
update_url = https://github.com/Fayenora/Robotics/1.20.1/forge/update.json/1.20/forge/update.json

project_id = 412082

# Loaders
fabric_loader_version = 0.16.7
fabric_api_version=0.92.2+1.20.1
forge_version = 47.2.0
neo_version = 47.1.79
neo_version_range = [47.1,)
loader_version_range = [4,)

# Dependencies
jei_version=15.3.0.4
cct_version=1.111.0
cobalt_version=0.9.3
cct_version_range=[1.111.0,1.112.0)
geckolib_version=4.4.8
geckolib_version_range=[4.4.0,)
parchment_version=1.20.1:2023.09.03
patchouli_version=84







