architectury {
    platformSetupLoomIde()
    forge()
}

def generatedResources = file("src/generated")

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

        mixinConfig "${mod_id}-common.mixins.json"
        mixinConfig "${mod_id}.mixins.json"
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "norabotics"
            programArgs "--existing", file("src/main/resources").absolutePath
            programArgs "--output", generatedResources.absolutePath
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}


processResources {

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta', 'update.json']) {
        expand rootProject.ext.replaceProperties + [project: project]
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"

    zip64 true
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

task updateJson {
    file('update.json').withWriter { w ->
        file('update_template.json').eachLine { line ->
            w << line.replaceAll("version", project.version) + System.getProperty("line.separator")
        }
        w.close()
    }
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.mod_id + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        maven {
            url = "https://www.cursemaven.com"
            allowInsecureProtocol = true
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir generatedResources }

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    //forge "net.neoforged:forge:${minecraft_version}-${neo_version}"

    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    modImplementation("au.edu.federation.caliko:caliko:1.3.8")
    forgeRuntimeLibrary("au.edu.federation.caliko:caliko:1.3.8")
    include("au.edu.federation.caliko:caliko:1.3.8")

    // JEI
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    // CC Tweaked
    modImplementation("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")
    implementation("cc.tweaked:cobalt:${cobalt_version}")
    forgeRuntimeLibrary("cc.tweaked:cobalt:${cobalt_version}")
    // Geckolib
    implementation("com.eliotlash.mclib:mclib:20")
    forgeRuntimeLibrary("com.eliotlash.mclib:mclib:20")
    modImplementation("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")

    // Runtime Mods
    modLocalRuntime("vazkii.patchouli:Patchouli:${minecraft_version}-${patchouli_version}-FORGE") // Patchouli
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))
    modLocalRuntime("curse.maven:tagtooltips-899941:4687165") // Item Tags
    modLocalRuntime("curse.maven:mekanism-268560:5662583") // Mekanism
    modLocalRuntime("curse.maven:cofh-core-69162:5374122") //CoFH Core
    modLocalRuntime("curse.maven:placebo-283644:5414631") // Placebo
    modLocalRuntime("curse.maven:apothic-attributes-898963:5634071") // Apothic Attributes
    modLocalRuntime("curse.maven:applied-energistics-2-223794:5641282") // Applied Energistics
    modLocalRuntime("curse.maven:pehkui-319596:5393101") // Pehkui
    modLocalRuntime("curse.maven:framework-549225:5692398")
    modLocalRuntime("curse.maven:curios-309927:5680164")
}
